"""
API Server: AlphaResearch AI Core
Description: FastAPI application serving as the primary entry point for the frontend.
It handles CORS, receives chat requests, passes them to the LangGraph orchestration 
engine, and manages the execution state and HTTP error handling.
"""

import os
import traceback
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv
from langchain_core.messages import HumanMessage

# Import the compiled LangGraph workflow
from graph import graph

# Load environment variables (.env)
load_dotenv()

# Initialize FastAPI application with production-grade metadata
app = FastAPI(
    title="AlphaResearch AI API", 
    description="Universal Multi-Agent Autonomous Research Platform"
)

# Configure CORS to allow communication from the Next.js frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ChatRequest(BaseModel):
    """Schema for incoming chat requests from the client."""
    message: str
    thread_id: str  # Unique ID to maintain conversation memory in LangGraph

@app.post("/chat")
async def chat_endpoint(request: ChatRequest):
    """
    Primary chat endpoint. Invokes the LangGraph workflow with the user's message
    and returns the final AI response or an interrupt status for clarification.
    """
    # Configure the LangGraph memory checkpointer with the specific thread_id
    config = {"configurable": {"thread_id": request.thread_id}}
    
    # Format the user's input as a LangChain HumanMessage
    inputs = {"messages": [HumanMessage(content=request.message)]}
    
    try:
        # Invoke the graph. Execution runs until it hits the END node.
        result = graph.invoke(inputs, config=config)
        
        # Extract the latest message generated by the AI
        final_messages = result.get("messages", [])
        last_ai_message = final_messages[-1].content if final_messages else "No response generated."
        
        # Check if the graph exited early due to the Clarity Agent's HITL trigger
        if result.get("clarity_status") == "needs_clarification":
            return {
                "status": "interrupt", 
                "response": last_ai_message
            }
        
        # Standard completion response
        return {
            "status": "completed",
            "response": last_ai_message
        }
        
    except Exception as e:
        # Log the full stack trace to the terminal for debugging
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)